language: python
python:
    - "2.6"
    - "2.7"
    - "3.3"
    - "3.4"
    - "pypy"
before_install:
    - sudo apt-get install -y libevent-dev
install:
    - python setup.py develop
    - pip install tox
script: tox
notifications:
    email: tarek@mozilla.com
    irc: "irc.freenode.org#mozilla-circus"
    on_success: change
after_success:
  # Report coverage results to coveralls.io
  - pip install coveralls
  - coveralls
