language: python
python:
    - "2.6"
    - "2.7"
    - "3.3"
install:
    - python setup.py develop
script: make test
notifications:
    email: tarek@mozilla.com
    irc: "irc.freenode.org#mozilla-circus"
    on_success: change
after_success:
  # Report coverage results to coveralls.io
  - pip install coveralls
  - coveralls
